name: CakeLang
version: '3.0'
main: si.f5.stsaria.cakeLang.CakeLang
api-version: '1.21'
author: stsaria
website: http://stsaria.f5.si

commands:
  cakelang:
    description: cakelang interpreter
    permission: cakelang
  fer:
    description: cakelang usercmd base
permissions:
  cakelang:
    description: cakelang command's permission
    default: op