name: AdvCommands
version: '3.0'
main: si.f5.stsaria.advCommands.AdvCommands
api-version: '1.21'
author: yudenOfSauce
website: http://stsaria.f5.si

commands:
  advcmd:
    description: interpreter
    permission: advcmd
  fer:
    description: advcmd usercmd base
permissions:
  advcmd:
    description: advcmd command's permission
    default: op